---
- hosts: alertmanager
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - alertmanager

- hosts: node_exporter
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter

- hosts: prometheus
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus

- hosts: grafana
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Add Grafana repository and import GPG key
      yum_repository:
        name: grafana
        description: Grafana Repository
        baseurl: https://rpm.grafana.com/oss/rpm
        gpgcheck: yes
        gpgkey: https://rpm.grafana.com/gpg.key
        enabled: yes

  roles:
    - grafana
